language: haskell

ghc:
 - "7.6"
 - "7.8"
 - "7.10"
 - "8.0"

install:
 - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
